### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Ezrabro** [anchovyyy/rice#1]
hey dude wassup?

i wanted to know if i want the exact same setup that you have right now
what should i do, step by step?

can i just copy all of your config and then I'm ready to go?

and finally, if i could copy your rice how can i edit and customize it?

bye bye

**Comment by anchovyyy** [comment]
Hey sorry for the late reply

yeah, u can just copy all my configs, though you might have to change some things.
from the top of my head, you'll have to change the temperature module in polybar to match yours, but there are probably more things

you can go through the config and read up online about what each thing does to change it to your liking, if you want to edit and customize it

let me know if you need help
